sudo: false

language: go

go:
  - 1.10.x
  - tip

install: true

script:
  - ls /home/travis/gopath/
  - ls /home/travis/gopath/src/
  - ls /home/travis/gopath/src/github.com/Timothylock/inventory-management/
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)