sudo: false

language: go

go:
  - 1.10.x
  - 1.x

git:
  depth: 1

before_install:
  - export GOPATH="$GOPATH:${TRAVIS_BUILD_DIR}"

install: true

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled